config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  resources :post_categories
  resources :categories
  resources :posts
  resources :users
  resources :comments
  resources :likes
  resources :follows

  get "/signup", to: "users#new", as: "signup"
  post '/users', to: "users#create"
  get "/users/:id/follow", to: "users#follow", as: "follows_with"
  # our login logic
  get "/feed", to: "posts#feed", as: "feed"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create", as: "sessions"

  delete "sessions", to: "sessions#destroy"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
  has_many :comments
  has_many :likes
  has_one_attached :profile_pic
  has_many :liked_posts, through: :likes, source: :post
  has_many :commented_posts, through: :comments, source: :post

  has_many :follows

  # :following_follows = The follow that you are giving to someone else
  # :class_name = The actual name of the class to be searched
  # :foreign_key = The actual foreign_key on the table to be compared to a User's id
  has_many :following_follows, class_name: "Follow", foreign_key: :follower_id
  has_many :followeds, through: :following_follows, source: :followed

  ##############################
  has_many :followed_follows, class_name: "Follow", foreign_key: :followed_id
  has_many :followers, through: :followed_follows, source: :follower

  # Returns an array of hashes to be converted to a timeline
  def compile_timeline
    array = []

    # Gather all likes, comments, and posts of people you follow
    self.followeds.each do |followed|
      stuff = followed.posts
      array << stuff
      stuff = followed.likes
      array << stuff
      stuff = followed.comments
      array << stuff
    end
    array.flatten!

    # Order them newest first
    # ordered_objects = array.sort_by(&:created_at)
    # Convert to array of hashes
    array.map! do |instance|
      hash = {}
      if instance.has_attribute?(:contents)
        hash[:action] = "commented on a post"
        hash[:post] = instance.post
        hash[:user] = instance.user
        hash[:created_at] = instance.created_at
      elsif instance.has_attribute?(:caption)
        hash[:action] = "posted a new post"
        hash[:post] = instance
        hash[:user] = instance.user
        hash[:created_at] = instance.created_at
      elsif instance.has_attribute?(:user_id)
        hash[:action] = "liked a post"
        hash[:post] = instance.post
        hash[:user] = instance.user
        hash[:created_at] = instance.created_at
      end
      hash
    end

    array.sort_by { |k| k[:created_at] }.reverse
    # byebug
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to posts_path
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @already_following = Follow.find_by(follower_id: current_user.id, followed_id: @user.id)
    @follow = Follow.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.valid?
      @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  def follow
    @user = User.find(params[:id])
    @followers = @user.followers
    @followeds = @user.followeds
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :profile_pic, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :profile_pic %>
  <%= f.file_field :profile_pic %><br>
  <%= f.submit %>
<% end %>

app/views/users/follow.html.erb
<h1><%= @user.username %></h1>
<h2>Following - <%= @user.followeds.count %> </h2>

<% @user.followeds.each do |f| %>
  <div class="followeds_div">
    <%= image_tag f.profile_pic %>
    <%= link_to f.username, user_path(f) %>
  </div>
<% end %>













<h2>Followers - <%= @user.followers.count %> </h2>
<% @user.followers.each do |f| %>
<div class="followers_div">
  <%= image_tag f.profile_pic %>
  <%= link_to f.username, user_path(f) %>
</div>
<% end %>

app/views/users/index.html.erb
<h1>User Profiles</h1>
<div class="users_container">
  <div class="row">
      <% @users.each do |user|  %>
      <div class="col-sm">
      <div class="card" style="width: 18rem;">
        <%= image_tag user.profile_pic, class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= user.username %></h5>
          <a href="<%= user_path(user) %>" class="btn btn-primary">See Profile</a>
        </div>
      </div>
    </div>
      <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1 class="brand"> <span class="oh">Öh</span>Snap</h1>
  <div class="new_wrapper"> <!-- this is where we are putting the grid -->
    <h2 class="h2login">New User</h2>
        <%= form_for @user do |f| %>
        <!-- <form> -->
          <p>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control"%>
          </p>

          <p>
            <%= f.label :username %>
            <%= f.text_field :username, class: "form-control" %>
          </p>

          <p>
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </p>

          <p>
            <%= f.label :password_confirmation, "Password Confirmation" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </p>

          <p>
            <%= f.label :profile_pic, "Profile Picture" %>
            <%= f.file_field :profile_pic, class: "form-control" %>
          </p>


          <p class="new_submit">
            <%= f.submit class: "btn btn-outline-primary" %>
          </p>
          <!-- </form> -->
        <% end %>
  </div>
</div>

app/views/users/show.html.erb
<body id="user_show_body">
  <h1>Profile Info</h1>
  <div class="profile_intro">
    <%= image_tag @user.profile_pic %>

    <div class="user_show_greeting">
      <p>Hello, <%= @user.name %>.</p>
      <p>Username: <%= @user.username %></p>
    </div>

  <div class="blue_box">
      <!-- FOLLOWERS -->
      <%= link_to "Following:  #{@user.following_follows.count}" , follows_with_path(@user) %>
      <%= link_to "Followers:  #{@user.followed_follows.count}" , follows_with_path(@user) %>
      <!-- END OF FOLLOWERS -->

      <div class="user_follow">
        <% if @already_following %>
        <%= link_to "Unfollow", follow_path(@already_following), class: "btn btn-outline-primary", method: :delete %>

        <% else %>
        <%= form_for @follow do |f| %>
        <%= f.hidden_field :follower_id, value: current_user.id %>
        <%= f.hidden_field :followed_id, value: @user.id %>
        <%= f.submit "Follow", class: "btn btn-outline-primary"%>
        <% end %>
        <% end %>
      </div>

      <% if current_user == @user %>
      <%= link_to "Edit Profile", edit_user_path(@user), method: :get %>
      <i class="fa fa-pencil" aria-hidden="true" style="font-size:24px"></i>

      <%= link_to "Delete Profile", user_path(@user), data: {:confirm => "Are you sure you want to delete your profile? \nThis cannot be undone."}, method: :delete %>
      <i class="fa fa-trash-o" aria-hidden="true" style="font-size:24px"></i>

      <% end %>
    </div>
  </div>

  <hr>

  <div class="user_post_section">
    <h2>All of <%= @user.username %>'s Posts</h2>
    <ul style="list-style-type: none;">
      <% @posts.each do |post| %>
      <li><%= "#{post.caption[0..15]}..." %> <%= link_to "See Post", post_path(post)%></li>
      <% end %>
    </ul>
  </div>
</body>