config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  resources :post_categories
  resources :categories
  resources :posts
  resources :users
  resources :comments
  resources :likes
  resources :follows

  get "/signup", to: "users#new", as: "signup"
  post '/users', to: "users#create"
  get "/users/:id/follow", to: "users#follow", as: "follows_with"
  # our login logic
  get "/feed", to: "posts#feed", as: "feed"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create", as: "sessions"

  delete "sessions", to: "sessions#destroy"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :liked_users, through: :likes, source: :user
  has_many :commented_users, through: :comments, source: :user
  has_one_attached :image

  #Validations
  validate :image_presence

  ### Methods
  # Validates image is attached
  def image_presence
    errors.add(:image, "Image must be attached.") unless image.attached?
  end

  # Custom setter for category names
  def category_names=(names)
    names.each do |name|
      unless name == ""
        category = Category.find_or_create_by(name: name)
        self.categories << category unless self.categories.include?(category)
      end
    end
  end

  # Custom getter for category names
  def category_names
    self.categories.map do |category|
      category.name
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController




  def index
    @array = current_user.compile_timeline
    # @comment = Comment.new
    # if logged_in?
    #   @posts = current_user.posts
    # else
    #   @posts = Post.all.reverse # or force a login
    # end
  end

  def new
    @post = Post.new
    @users = User.all
    @post_categories = @post.category_names
    @categories = Category.all
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      category = Category.find_by(name: params[:post]["category_ids"])
      postcat = PostCategory.find_or_create_by(post: @post, category: category)
      redirect_to post_path(@post)
    else
      @users = User.all
      @post_categories = @post.category_names
      @categories = Category.all
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @categories = @post.categories
    @comment = Comment.new

    @liked = Like.find_by(user: current_user, post: @post)
    @like = Like.new
    @number_of_likes = @post.likes.count
    # byebug
  end

  def edit
    @post = Post.find(params[:id])
    @post_categories = @post.category_names
    @categories = Category.all
  end

  def update
    @post = Post.find(params[:id])
    @post.post_categories.destroy_all
    @post.assign_attributes(post_params)
    if @post.valid?
      @post.save
      category = Category.find_by(name: params[:post]["category_ids"])
      postcat = PostCategory.find_or_create_by(post: @post, category: category)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  def feed
    @posts = Post.all.reverse
    @comment = Comment.new
  end

  private
  def post_params
    params.require(:post).permit(:caption, :user_id, :image, category_names: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f| %>
<%= f.label :image %>
<%= f.file_field :image %><br>
  <%= f.label :caption %>
  <%= f.text_field :caption %><br>
  <%= f.hidden_field :user_id, value: @post.user_id %>

    <label for="post[category_names][]">Categories</label>
    <input name="post[category_names][]" list="categories_autocomplete" value="<%= @post_categories[0] %>" >
    <input name="post[category_names][]" list="categories_autocomplete" value="<%= @post_categories[1] %>" >
    <input name="post[category_names][]" list="categories_autocomplete" value="<%= @post_categories[2] %>" >

    <datalist id="categories_autocomplete">
      <% @categories.each do |category| %>
        <option value="<%= category.name %>">
      <% end %>
    </datalist>


  <%= f.submit %>
<% end %>

app/views/posts/feed.html.erb
<h1>Recent Posts</h1>
  <div class="feed_container justify-content-center">
    <div class="row">
      <div class="card-deck" style="align-content: space-evenly;">
      <% @posts.each do |post| %>
          <div class="col-sm-4">
            <div class="card mb-3 ">
              <div class="card-body">
                <a href="<%= post_path(post) %>"><%= image_tag post.image, class:"rounded card-img-top shadow" %></a>

            <blockquote>
              <br>
              <h2>
                "<%= post.caption %>"
              </h2>
              <footer class=""><%= link_to post.user.username, user_path(post.user) %><br><%= time_ago_in_words(post.created_at) %> ago</footer>
            </blockquote>

              </div>
            </div>
          </div>
              <% end %>
        </div>




      </div>
  </div>

app/views/posts/index.html.erb
<h1>My Timeline</h1>
<div class="feed_container justify-content-center">
  <div class="row">
    <div class="card-deck" style="align-content: space-evenly;">
    <% @array.each do |item| %>
        <div class="col-sm-4">
          <div class="card mb-3">
            <div class="card-body">
              <%= link_to item[:user].username, item[:user] %> <%= item[:action] %>
              <a href="<%= post_path(item[:post]) %>"><%= image_tag item[:post].image, class:"rounded card-img-top shadow" %></a>

          <blockquote>
            <br>
            <h2>
              "<%= item[:post].caption %>"
            </h2>
            <footer class=""><%= link_to item[:post].user.username, user_path(item[:user]) %><br><%= time_ago_in_words(item[:created_at]) %> ago</footer>
          </blockquote>

            </div>
          </div>
        </div>
            <% end %>
      </div>
      </div>
      </div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="brand"> <span class="oh">Öh</span>Snap</h1>
    <div class="new_wrapper">
      <h2 class="h2login">New Post</h2>
          <%= form_for @post, multipart: true do |f| %>
          <div class="split_two">
              <p>
                <%= f.label :image %>
                <%= f.file_field :image, class: "form-control" %>
              </p>
              <p class="post_cap">
                <%# f.label :caption %>
                <%= f.text_field :caption, placeholder: "Caption", class: "form-control" %>
              </p>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.submit class: "btn btn-outline-primary" %>
            </div>
            <div class="split_two">
              <label for="post[category_names][]">Categories</label>
              <input name="post[category_names][]" list="categories_autocomplete" class="form-control">
              <br>
              <input name="post[category_names][]" list="categories_autocomplete" class="form-control">
              <br>
              <input name="post[category_names][]" list="categories_autocomplete" class="form-control">

              <datalist id="categories_autocomplete">
                <% @categories.each do |category| %>
                <option value="<%= category.name %>">
                  <% end %>
                </datalist>
            </div>
            <% end %>
      </div>
    </div>

app/views/posts/old_index.html.erb
<h1>My Timeline</h1>

<% @posts.each do |post|  %>

<div class="post_container">
  <div class="row">
  <div class="posts col-sm">
    <div class="post_user_div">
      <%= link_to post.user.username, user_path(post.user) %>
    </div>
    <div class="post_img_div">
      <%= image_tag post.image, class: "post_img" %>
    </div>
    <div class="post_caption_div">
      <%= link_to post.caption, post_path(post), class: "post_caption" %>
    </div>
  </div>

  <div class="comments col-sm">
    <h3>Comments</h3>
    <div class="all_comments">
      <% post.comments.each do |comment| %>
      <%= link_to comment.user.username, user_path(comment.user) %> :
      <br>
      <%= comment.contents %>
      <br>
      <% end %>
    </div>
    <%= form_for @comment do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.text_area :contents %>

    <%= f.submit "⇨" %>
    <% end %>
  </div>
  </div>
</div>
  <hr>
<% end %>

app/views/posts/show.html.erb
<blockquote class="blockquote">
  <h1 class="mb-0"><%= @post.caption %></h1>
</blockquote>

<div class="post_show_wrapper">
  <div class="post_show_left">
    <!-- making some crazy stuff -->
    <div class="card mb-3" style= "width: 20rem;">
      <div class="flip-container interests" ontouchstart="this.classList.toggle('hover');">
        <div class="flipper">

				      <div class="front">
                <%= image_tag @post.image, class: "post_img" %>
                <%= @post.caption %>
              </div>

              <div class="back">
                <h3 class= "post_cat">Categories</h3>
                <!-- <ul style="list-style: none;"> -->
                  <% @categories.each do |category|%>
                  <p><%= category.name %></p>
                <!-- </ul> -->
                <% end %>
              </div>
        </div>
      </div>
    </div>



    <!-- end of crazy stuff -->
    <% if @liked %>
    <div class="liked">
      <%= link_to "Unlike", like_path(@liked), method: :delete  %>
      <i class="fa fa-thumbs-o-up" style="font-size:24px"></i> + <%= @number_of_likes %>
      <!-- <div class="edit_delete"> -->
        <% if current_user == @user %>
          <%= link_to "Edit Post", edit_post_path(@post), method: :get %>
          <i class="fa fa-pencil" aria-hidden="true" style="font-size:24px"></i>

          <%= link_to "Delete Post", post_path(@post), data: {:confirm => "Are you sure you want to delete this post? \nThis cannot be undone."}, method: :delete %>
          <i class="fa fa-trash-o" aria-hidden="true" style="font-size:24px"></i>
        <% end %>
      <!-- </div> -->
    </div>
    <% else %>
    <%= form_for @like do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id%>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.submit "Like   👍🏼", class: "btn btn-primary " %> + <%= @number_of_likes %>
    <% end %>
    <% end %>


  </div>




  <div class="post_show_right">
    <div class="all_comments">
      <% @post.comments.each do |comment| %>
      <%= link_to comment.user.username, user_path(comment.user) %> :
      <br>
      <%= comment.contents %>
      <br>
      <% end %>
    </div>

    <br>
    <%= form_for @comment do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.text_area :contents %>

    <%= f.submit "⇨" %>
    <% end %>
  </div>
</div>

<hr>

<footer class="blockquote-footer">Posted by: <%= link_to @user.username, user_path(@user) %></footer>