config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  resources :post_categories
  resources :categories
  resources :posts
  resources :users
  resources :comments
  resources :likes
  resources :follows

  get "/signup", to: "users#new", as: "signup"
  post '/users', to: "users#create"
  get "/users/:id/follow", to: "users#follow", as: "follows_with"
  # our login logic
  get "/feed", to: "posts#feed", as: "feed"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create", as: "sessions"

  delete "sessions", to: "sessions#destroy"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  add_breadcrumb "home", :feed_path
  def index
    @categories = Category.all
    add_breadcrumb "index", categories_path
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts.reverse
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<div class="container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= render_breadcrumbs :separator => ' / ' %></li>
  </ol>
</div>

<div class="users_container">
  <div class="row">
    <% @categories.each do |category|  %>
      <div class="col-sm">
        <div class="card" style="width: 18.9rem;">
          <% post = category.posts[-1] %>
          <% unless post == nil %>
          <%= image_tag post.image %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= category.name %></h5>
            <a href="<%= category_path(category) %>" class="btn btn-primary">View Category</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<div class="feed_container justify-content-center">
  <div class="row">
    <div class="card-deck" style="align-content: space-evenly;">
    <% @posts.each do |post| %>
        <div class="col-sm-4">
          <div class="card mb-3">
            <div class="card-body">
              <a href="<%= post_path(post) %>"><%= image_tag post.image, class:"rounded card-img-top shadow" %></a>

          <blockquote>
            <br>
            <h2>
              "<%= post.caption %>"
            </h2>
            <footer class=""><%= link_to post.user.username, user_path(post.user) %><br><%= time_ago_in_words(post.created_at) %> ago</footer>
          </blockquote>

            </div>
          </div>
        </div>
            <% end %>
      </div>