config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  resources :post_categories
  resources :categories
  resources :posts
  resources :users
  resources :comments
  resources :likes
  resources :follows

  get "/signup", to: "users#new", as: "signup"
  post '/users', to: "users#create"
  get "/users/:id/follow", to: "users#follow", as: "follows_with"
  # our login logic
  get "/feed", to: "posts#feed", as: "feed"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create", as: "sessions"

  delete "sessions", to: "sessions#destroy"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OhSnap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,800" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-lg">
  <a class="navbar-brand" href="#"><span class="oh">Öh</span>Snap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if logged_in? %>
      <li class="nav-item active">
        <a class="nav-link active" href="<%= new_post_path %>">+ Post <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= user_path(current_user) %>">My Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= posts_path %>">My Timeline</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= users_path %>">All Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= categories_path %>">Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= feed_path %>">Feed</a>
      </li>
      <li class="nav-item">
        <%= link_to "Logout", sessions_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="<%= login_path %>">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_path %>">Sign Up</a>
        </li>
        <% end %>
    </ul>
    <ul class="navbar-nav">
            <li class="nav-item">
              <% if logged_in? %>
                <span class="navbar-text" id="nav_greeting">
                  Hello, <%= current_user.name %>!!
                </span>
              <% end %>
            </li>
    </ul>
  </div>
</nav>


    <br>
    <br>
    <br>
    <%= yield %>
  </body>
</html>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>